api:
  - ".github/workflows/build.yml"
  - "config/docker/api.Dockerfile"
  - "config/flatbuffers/**"
  - "api/**"

app:
  - ".github/workflows/build.yml"
  - "config/docker/app.Dockerfile"
  - "app/**"

cmp:
  - ".github/workflows/build.yml"
  - "clients/cpp/**"
  - "config/docker/cmp.Dockerfile"
  - "config/flatbuffers/**"
  - "cmp/**"

ops:
  - ".github/workflows/build.yml"
  - "devops/**"

web:
  - ".github/workflows/build.yml"
  - "web/**"
