version: '3'
services:

  weasel_redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./local/data/redis:/data
    restart: always

  weasel_mongo:
    image: mongo:4-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:weaselmaster
      - MONGO_INITDB_ROOT_PASSWORD:weaselsecret
    volumes:
      - ./local/data/mongo:/data/db
      - ./devops/mongo/entrypoint/:/docker-entrypoint-initdb.d/
    restart: always

  weasel_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - ./local/data/elastic:/usr/share/elasticsearch/data
    restart: always

#  weasel_kibana:
#    image: docker.elastic.co/kibana/kibana-oss:7.8.0
#    ports:
#      - 5601:5601
#    volumes:
#      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#    depends_on:
#      - weasel_elastic
#    restart: always
