version: "3"
services:
  weasel_api:
    image: 727591621296.dkr.ecr.us-east-2.amazonaws.com/weasel-api:1.4.0
    environment:
      ENV_FILE: prod
      AUTH_JWT_SECRET: <SECRET>
      AUTH_COOKIE_SECRET: <SECRET>
      MAIL_TRANSPORT_HOST: <SECRET>
      MAIL_TRANSPORT_USER: <SECRET>
      MAIL_TRANSPORT_PASS: <SECRET>
      MAIL_TRANSPORT_PORT: 587
      WEBAPP_ROOT: <UNKNOWN>
    volumes:
      - ./local/data/weasel:/opt/local/data/weasel
      - ./local/logs/api:/opt/local/logs/api
    depends_on:
      - weasel_minio
      - weasel_mongo
      - weasel_redis
    restart: always

  weasel_webapp:
    image: 727591621296.dkr.ecr.us-east-2.amazonaws.com/weasel-app:1.4.0
    ports:
      - 80:80
    depends_on:
      - weasel_api
    restart: always

  weasel_cmp:
    image: 727591621296.dkr.ecr.us-east-2.amazonaws.com/weasel-cmp:1.4.0
    volumes:
      - ./local/data/weasel:/opt/local/data/weasel:ro
      - ./local/logs/cmp:/opt/local/logs/cmp
    depends_on:
      - weasel_api
    restart: always

  weasel_redis:
    image: redis:6-alpine
    volumes:
      - ./local/data/redis:/data
    # ports:
    #  - 6379:6379
    restart: always

  weasel_minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    environment:
      MINIO_ROOT_USER: weaseluser
      MINIO_ROOT_PASSWORD: weaselpass
    volumes:
      - ./local/data/minio:/data
    # ports:
    #   - 9000:9000
    command: server /data
    restart: always

  weasel_mongo:
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: weaseluser
      MONGO_INITDB_ROOT_PASSWORD: weaselpass
    volumes:
      - ./local/data/mongo:/data/db
      - ./devops/mongo/mongod.conf:/etc/mongod.conf
      - ./devops/mongo/entrypoint/:/docker-entrypoint-initdb.d/
    # ports:
    #   - 27017:27017
    command: --config /etc/mongod.conf
    restart: always
