# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-java-main

on:
  push:
    branches:
      - main
      - development
      - 'feature/**'

jobs:

  test-native:
    name: unittest-native
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: authenticate to aws
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS_PUBLIC }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET_ACTIONS_PUBLIC }}
          aws-region: us-east-2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew build
      - name: push docs to aws
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          tar -zcf java-docs-external.tar.gz touca/build/docs/javadoc
          aws s3 cp java-docs-external.tar.gz ${{ secrets.AWS_DEV_S3_BUCKET_BUILD }}/v1.4.0/
      - name: push coverage to aws
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          tar -zcf python-test-coverage.tar.gz touca/build/reports/jacoco/test/html
          aws s3 cp python-test-coverage.tar.gz ${{ secrets.AWS_DEV_S3_BUCKET_BUILD }}/v1.4.0/
      - name: cleanup gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
